// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveySystem.Data;

namespace SurveySystem.Migrations
{
    [DbContext(typeof(SurveyContext))]
    [Migration("20190424173532_test8")]
    partial class test8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SurveySystem.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("QuestionId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("SurveySystem.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SurveySystem.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("SurveyId");

                    b.Property<Guid?>("VoteId");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.HasIndex("VoteId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SurveySystem.Models.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Question");

                    b.Property<Guid>("TypeId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("SurveySystem.Models.SurveyAnswerTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("SurveyId");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyAnswerTemplates");
                });

            modelBuilder.Entity("SurveySystem.Models.SurveyGroup", b =>
                {
                    b.Property<Guid>("SurveyId");

                    b.Property<Guid>("GroupId");

                    b.HasKey("SurveyId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("SurveyGroups");
                });

            modelBuilder.Entity("SurveySystem.Models.SurveyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SurveyTypes");
                });

            modelBuilder.Entity("SurveySystem.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ClientId");

                    b.Property<Guid?>("VoterId");

                    b.HasKey("Id");

                    b.HasIndex("VoterId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("SurveySystem.Models.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("SurveySystem.Models.Answer", b =>
                {
                    b.HasOne("SurveySystem.Models.Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("SurveySystem.Models.Question", b =>
                {
                    b.HasOne("SurveySystem.Models.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId");

                    b.HasOne("SurveySystem.Models.Vote")
                        .WithMany("Questions")
                        .HasForeignKey("VoteId");
                });

            modelBuilder.Entity("SurveySystem.Models.Survey", b =>
                {
                    b.HasOne("SurveySystem.Models.SurveyType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SurveySystem.Models.SurveyAnswerTemplate", b =>
                {
                    b.HasOne("SurveySystem.Models.Survey", "Survey")
                        .WithMany("Templates")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SurveySystem.Models.SurveyGroup", b =>
                {
                    b.HasOne("SurveySystem.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SurveySystem.Models.Survey", "Survey")
                        .WithMany("Groups")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SurveySystem.Models.Vote", b =>
                {
                    b.HasOne("SurveySystem.Models.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId");
                });
#pragma warning restore 612, 618
        }
    }
}
